name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pylint bandit

      - name: Code Quality
        run: |
          pylint app.py || true
          bandit -r . --exclude venv -s B104,B101

      - name: Run tests
        run: pytest -v

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Build App
        run: echo "✅ Flask App Build Successful"

  deploy-staging:
    needs: build
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 (Staging)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "🚀 Deploying to STAGING EC2"
            cd $APP_DIR || git clone -b staging https://github.com/VenkyHM/flask_Practice_cicd.git $APP_DIR && cd $APP_DIR
            git fetch origin
            git reset --hard origin/staging
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            python3 -m venv venv || true
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install gunicorn
            sudo systemctl daemon-reload
            sudo systemctl restart flask-app
            sudo systemctl restart nginx
            echo "✅ Deployment Done"

  deploy-production:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 (Production)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.PROD_EC2_USER }}
          key: ${{ secrets.PROD_EC2_SSH_KEY }}
          script: |
            set -e
            echo "🚀 Deploying to PRODUCTION EC2"
            cd $APP_DIR || git clone -b main https://github.com/VenkyHM/flask_Practice_cicd.git $APP_DIR && cd $APP_DIR
            git fetch origin
            git reset --hard origin/main
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            python3 -m venv venv || true
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install gunicorn
            sudo systemctl daemon-reload
            sudo systemctl restart flask-app
            sudo systemctl restart nginx
            echo "✅ Production Deployment Done"
